### ISSUE TITLE
Structure of this repository

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/clams-aapb-annotations#9] opened 2022-12-15 14:02 UTC
The current structure of the repository does not reflect the proposal in issue #2.

- There is more structure in the `guidelines` directory, which is fine. 
- There is less structure in the `golds` directory, where for example we have `golds/sample-ner` instead of `golds/ner/sample-ner` (also note that we were envisioning having a date on the project.
- We did realize back in the days that the `uploads` directory could not have the same thematic subdivision as the `golds` directory because an upload could technically have several kinds of annotations (for example, bars-and-tone and slates). However, it would be nice to have some more structure than we have now by grouping together uploads that can use the same `process.py` script.

**Comment by keighrim** [comment] 2023-04-26 14:39
closing as duplicate of #2 .

**Closed by keighrim** 2023-04-26 14:39 UTC
Labels: :v:2
